#!/bin/bash

#Author Felipe Macedo

declare -a files

list_files(){


    for f in *; do 
		if [[ -f "$f" && ! -L "$f" ]]; then 
        	files+=("$f")
		fi
	done
}

list_directories(){

	for d in *; do
		if [[ -d "$d" && ! -L "$d" ]]; then 
			files+=("$d")
		fi
	done
	
}

list_all(){
	for file in *; do 
		files+=("$file")
	done 
}


#Generate character spaces
generate_spaces(){
    n_spaces=$@
    
    while [ $n_spaces -ge 1 ]; do
        echo -n "*"
        n_spaces=$(($n_spaces -1))
    done
}

#Show directories
show_dir(){
    local index=0;
	local len_files=${#files[@]} #Length o the array
	
	clear

	if [ $len_files -eq 0 ]; then
		list_all
		len_files=${#files[@]}
	fi	
    
    echo
    echo
    echo "+-------+------------------------+"
    echo "| INDEX |       DIRECTORY        |"
    echo "+-------+------------------------+"
    ## 7 spaces - max 10 latters - max 7 more spaces | total of 24 characters
	for i in `seq 0 $((len_files - 1))`; do
        len_name=${#files[$i]}
        pos_sp=0

        file=${files[$i]//" "/"_"} ##Replace spaces for underline
        if [ $len_name -gt 10 ]; then
            pos_sp=7
        else
            pos_sp=$(( 17 - $len_name ))
        fi

        printf "|  %2d   |" $index
        generate_spaces 7
        printf "%.10s" $file    
        generate_spaces $pos_sp
        echo "|"

        index=$(($index+1))
    
    done
    echo "+-------+------------------------+"
}

#Show a help menu
help_me(){
    echo
    echo "+----+---------------------------------+"
    echo "| dbn [options] [arguments]            |"
    echo "|                                      |"
    echo "| -c | Copy the name of a directory    |"
    echo "| -d | Enter the selected directory    |"
    echo "| -h | Exihibit this menu              |"
    echo "| -l | List content of the directory   |"
    echo "+----+---------------------------------+"
    echo
   
}

#Enter a specific directory
go_dir(){
	local len=${#files[@]}
	clear
	
	if [ $len -eq 0 ]; then
		list_all
		len=${#files[@]}
	fi

    if [ $# -eq 0 ]; then #Verify if a index has been passed. $# == 0
    
        echo "Specify one directory"
        echo
        echo "Correct usage: dbn -d 1"
        return;
    fi

    if [ $@ -ge 0 -a $@ -le $len ]; then #Verify if the index is inside the bound. [0,len - 1]
        cd "$PWD/${files[$@]}";
        bash;
    else
        echo "Index out of bound"
        echo "Index range [0-$(($len-1))]"
    fi
}

copy_dir_name(){
    local len=${#files[@]}
	clear

    if [ $# -eq 0 ]; then
        echo "Specify one File"
        echo
        echo "Correct usage: dbn -c 0"
        return;
    fi

    if [ $@ -ge 0 -a $@ -le $len ]; then
        
        echo ${files[$@]} | xclip -sel clip
        echo "Copied: ${files[$@]}"
		return;
    else
        echo "Index out of bound"
        echo "Index range [0-$(($len -1))]"
		return; 
    fi
    
}


commands=($@) ##Commands to execute

for i in `seq 0 $#`; do
    case ${commands[$i]} in
        -c) copy_dir_name ${commands[${i+2}]};;
        -g) go_dir ${commands[${i+2}]};;
		-f) list_files;;
		-d) list_directories;;
        -h) help_me;;
        -l) show_dir;;
    esac
        
done
